name: Flutter action
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2.12.0
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --debug --obfuscate --split-debug-info=symbols/
    - name: Generate release tag
      id: tag
      run: |
        echo "release_tag=APK_$(date +'%Y.%m.%d_%H-%M')" >> $GITHUB_ENV
    - name: Upload APK
      uses: ncipollo/release-action@v1.13.0
      with:
        tag: ${{ env.release_tag }}
        artifacts: build/app/outputs/flutter-apk/*.apk
        token: ${{ secrets.GITHUB_TOKEN }}