name: Flutter action

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: actions/setup-java@v2.3.1
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: subosito/flutter-action@v1.5.3
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --debug
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
